### ISSUE TITLE
Production-ready?

### ISSUE THREAD

**Issue by thomascharbit** [micwallace/magento2-threshold-taxes#1]
Hi,

Your extension looks promising!
Are you now using it in production or do you think it can be used safely if tested correctly before going to production?

Thanks

**Comment by micwallace** [comment]
Hi Thomas,

Not yet, but probably in the next month (still working on other brexit related stuff haha). We did find a infinite loop bug that was fixed today. I'll update github tomorrow with the fix.

Even with the fix, I provide no guarantees and it may not work as expected for your store setup. So definitely test! However the extension doesn't add any irreversible changes so if you do run into any strange issues just disable the module and it should be back to normal.

On 1 February 2021 9:34:58 pm AEDT, Thomas Charbit <notifications@github.com> wrote:
>Hi,
>
>Your extension looks promising!
>Are you now using it in production or do you think it can be used
>safely if tested correctly before going to production?
>
>Thanks
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/magento2-threshold-taxes/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thomascharbit** [comment]
Thanks for the feedback, i will keep an eye on it :)
